### ISSUE TITLE
[Bug report] Event target compatibility with Safari

### ISSUE THREAD

**Issue by duxiaofeng-github** [chmanie/o9n#2]
hi, @chmanie. when o9n.orientation.onchange being fired under Safari. The event target seens not a standard screen.orientation object?

I figure out it's a non-standard implement by Safari. Safari pass a window object when the event being fired.

Could you fix this?

---

Here is a screen shot:

iOS safari ("5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1"):
![image](https://cloud.githubusercontent.com/assets/1694541/25520990/a0debb0c-2c30-11e7-90dc-1af458a30c9a.png)

Chrome ("5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.68 Mobile Safari/537.36"):
![image](https://cloud.githubusercontent.com/assets/1694541/25521237/62f603a8-2c31-11e7-90d5-6b711e32eaa3.png)

**Comment by chmanie** [comment]
Hey, thank you for reporting this! I'll look into it!

**Comment by chmanie** [comment]
The specs don't really specify the event targets. However I decided to normalize for the chrome implementation for v2.

**Comment by chmanie** [comment]
I published v2 and it should be fixed in there.

**Comment by duxiaofeng-github** [comment]
great job, thx
